### ISSUE TITLE
我之前上传的文章不见了

### ISSUE THREAD

**Issue by Freakwill** [luaChina/lua-china#1]
我之前上传的文章不见了。我又重新写了几篇，我希望不要再弄丢了。这个社区怎么那么冷清？

**Comment by junwei000** [comment]
实在抱歉，前两天一次误操作导致数据库的一些数据丢失了，保证之后绝对不会再出现此类事故，我在群里说了这个事情，你有兴趣的话可以去网站首页找到二维码加群，我们目前才是启动阶段，所以都是些熟人在慢慢做这个社区，相信之后人会越来越多的，也非常感谢你参与推动社区的发展 :)，另外你发了一些测试文章我先在后台操作帮你放在草稿箱里了哈

**Comment by junwei000** [comment]
另外，你之前发布文章触发了一个 emoji 的 bug，这个上报 log 了，我看到后已经修复了~
